---
- name: 'Download do arquivo de instalação do WordPress'
  get_url:
    url: 'https://wordpress.org/wordpress-4.0.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompactando o arquivo de instação do WordPress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: true

- name: 'Copiando arquivo de configuração do WordPress'
  copy:
    src: '{{ wp_install_path }}/wp-config-sample.php'
    dest: '{{ wp_install_path }}/wp-config.php'
    remote_src: yes
  become: true

- name: 'Configurando o arquivo wp-config.php com os dados de banco de dados'
  replace:
    path: '{{ wp_install_path }}/wp-config.php'
    regexp: '{{ item.regex }}'
    replace: '{{ item.value }}'
  with_items:
    - { regex: 'database_name_here', value: '{{ wp_db_name }}' }
    - { regex: 'username_here', value: '{{ wp_db_user }}' }
    - { regex: 'password_here', value: '{{ wp_db_pass }}' }
    - { regex: 'localhost', value: '{{ wp_db_ip }}' }
  become: true

- name: 'Configura Apache para servir Wordpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/'
  become: true
  notify:
    - restart apache